language: node_js
cache:
  directories:
    - '$HOME/.npm'
branches:
  only:
    - master
install: npm ci
script:
  - npm run lint
  - npm run build
deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  local_dir: public
  skip_cleanup: true
  on:
    branch: master
