language: node_js
branches:
  only:
  - master
before_install: npm install -g npm@5.7.1
install: npm ci
script:
  - npm run lint
  - npm run build
deploy:
  edge:
    branch: v1.8.47
  local_dir: public
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
