language: node_js
install: yarn install
script:
  - npm run lint:js
  - npm run build
deploy:
  local_dir: public
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
