language: node_js
cache:
  directories:
    - "$HOME/.npm"
branches:
  only:
  - master
before_install: npm install -g npm@6.0.0
install: npm ci
script:
  - npm run lint
  - npm run build
deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master
  skip_cleanup: true
